version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MONGODB_URI=mongodb+srv://kelvinmbote:kevokevo@yolo-1.oodfc3i.mongodb.net/yolo-1
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - backend-data:/app/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - frontend-data:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
  frontend-data:
