apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: kevjmbote/client:2883c4d
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://backend-service:5000
