apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: kevjmbote/backend:ff93b2b
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mmongodb+srv://kelvinmbote:kevokevo@yolo-1.oodfc3i.mongodb.net/yolo-1?retryWrites=true&w=majority
